name: PIFu
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- opencv
- pytorch=1.1.0
- pillow
- scikit-image
- tqdm
- pyembree
- shapely
- rtree
- trimesh
- numpy
- pip
  pip:
  - xxhash
  - PyOpenGL
  - pyexr
